services:
  web:
    build: .
    ports:
      - "8058:8058"
    volumes:
      - ./start.sh:/app/start.sh
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "./start.sh"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
          pids: 100
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped