services:
  llms:
    build:
      context: ..
      dockerfile: dockers/Dockerfile.dev
      args:
        - SUPERUSER=$SUPERUSER
    hostname: $HOSTNAME
    container_name: ${SUPERUSER}_llms
    ports:
      - "8058:8058"
    volumes:
      - ../start.sh:/home/$SUPERUSER/LLMS/start.sh
      - ../api/:/home/$SUPERUSER/LLMS/api/
      - ../docs/:/home/$SUPERUSER/LLMS/docs/
      - ../requirements.txt:/home/$SUPERUSER/LLMS/requirements.txt
      - ../nginx.conf:/etc/nginx/nginx.conf
      - ../logs:/var/log/app
    env_file:
      - .env
    command: >
      bash -c ". ${SUPERUSER}_venv/bin/activate && ./start.sh"
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
          pids: 100
        reservations:
          cpus: '0.5'
          memory: 2G
    restart: unless-stopped