FROM python:3.13

RUN apt-get update \
    && apt-get install -y \
    nginx \
    && rm -rf /var/lib/apt/lists/*

COPY ../nginx.conf /etc/nginx/nginx.conf

WORKDIR /lolilmeows

COPY ../api ./api
COPY ../docs ./docs
COPY ../requirements.txt .
COPY ../start.prod.sh .
COPY ../LICENSE .

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x start.prod.sh